Repository VisualGameData/VIGAD, pull requests merged in 2022-12, with the labels that each got.

#47 fix: Only Vigad.ts has access to StreamHandler instance
  src/components/MainVideoStream.vue
  src/proc/Vigad.ts
  src/views/SourcesView.vue
Labels: improvement

#59 feat: Adapt to MVP mock up
  src/App.vue
  src/components/LogOutput.vue
  src/components/MainVideoStream.vue
  src/components/ViewComponent.vue
  src/components/capture-area/CaptureAreaMetaProperties.vue
  src/components/capture-area/CaptureAreaSearchValue.vue
  src/components/capture-area/RegexInput.vue
  src/composables/useForceRerender.ts
  src/composables/useRunning.ts
  src/main.ts
  src/plugins/vuetify.ts
  src/views/RegexView.vue
  src/views/RunPage.vue
  src/views/SourcesView.vue
Labels: Phase: Elaboration, RUP: Implementation, improvement

#61 Fix: dynamic preview sizing on window size change
  src/App.vue
  src/components/MainVideoStream.vue
Labels: Phase: Elaboration, RUP: Implementation, improvement

#58 feat: tesseract implementation
  index.html
  src/composables/useRunning.ts
  src/proc/TesseractHandler.ts
  src/proc/Vigad.ts
Labels: enhancement, Phase: Elaboration, RUP: Implementation

#64 fix(capture-area): fix scaling
  src/components/MainVideoStream.vue
  src/proc/CaptureArea.ts
  src/proc/TesseractHandler.ts
  src/proc/Vigad.ts
Labels: Phase: Elaboration, RUP: Implementation, improvement

#67 Feat/56 configuration for regex inputs
  src/components/LogOutput.vue
  src/components/capture-area/AfterConstraint.vue
  src/components/capture-area/BeforeConstraint.vue
  src/components/capture-area/CaptureAreaSearchValue.vue
  src/components/capture-area/RegexInput.vue
  src/components/capture-area/ValueRegex.vue
  src/proc/TesseractHandler.ts
  src/proc/regex/Regex.ts
  src/views/RegexView.vue
  src/views/RunPage.vue
Labels: Phase: Construction, RUP: Implementation, improvement

#70 fix(regex): matching issues
  docs/proc-uml.svg
  src/components/MainVideoStream.vue
  src/proc/Vigad.ts
  src/proc/regex/Regex.ts
  src/proc/regex/RegexHandler.ts
Labels: bug, Phase: Construction, RUP: Implementation

#73 feat: new log design and capture area tooltip
  src/App.vue
  src/components/LogOutput.vue
  src/components/MainVideoStream.vue
  src/views/RunPage.vue
Labels: Phase: Construction, RUP: Implementation, improvement
