Repository VisualGameData/VIGAD, pull requests merged in 2023-04, with the labels that each got.

#86 feat(chore): add move to next sprint workflow
  .github/workflows/next-iteration.yml
Labels: Phase: Construction, RUP: Project Management, improvement

#95 feat(tests): setup vitest unit testing framework with sample unit test
  .gitignore
  electron/main/index.ts
  package-lock.json
  package.json
  src/App.vue
  src/assets/images/logo.png
  src/components/LogOutput/LogOutput.vue
  src/components/MainVideoStream/MainVideoStream.vue
  src/components/ViewComponent/ViewComponent.test.ts
  src/components/ViewComponent/ViewComponent.vue
  src/components/capture-area/AfterConstraint/AfterConstraint.vue
  src/components/capture-area/BeforeConstraint/BeforeConstraint.vue
  src/components/capture-area/CaptureAreaSearchValue/CaptureAreaSearchValue.vue
  src/components/capture-area/ValueRegex/ValueRegex.vue
  src/views/RegexView.vue
  src/views/RunPage.vue
  src/views/SourcesView.vue
  vite.config.ts
Labels: Phase: Construction, RUP: Implementation, improvement

#117 feat(session): implement settings mock up
  src/App.vue
Labels: enhancement, Phase: Construction, RUP: Implementation

#120 fix(capturing): added alerts and disabled start button
  src/views/RegexView.vue
  src/views/RunPage.vue
Labels: bug, Phase: Construction, RUP: Implementation

#128 fix: update packages
  package-lock.json
  package.json
  src/components/ViewComponent/ViewComponent.vue
Labels: Phase: Construction, RUP: Implementation, improvement

#129 feat: implement notification system
  src/App.vue
  src/composables/useNotificationSystem.ts
Labels: enhancement, Phase: Construction, RUP: Implementation
