Repository VisualGameData/VIGAD, pull requests merged in 2023-05, with the labels that each got.

#140 feat: generate token and create own token
  src/App.vue
Labels: enhancement, Phase: Construction, RUP: Implementation

#143 feat:no fullscreen in settings anymore
  src/App.vue
Labels: Phase: Construction, RUP: Implementation, improvement

#145 fix: various ts issues
  src/components/ViewComponent/ViewComponent.test.ts
  src/proc/regex/RegexHandler.ts
  src/views/SourcesView.vue
Labels: bug, Phase: Construction, RUP: Implementation

#147 feat: setup test automation
  .github/workflows/test-coverage.yml
Labels: enhancement, Phase: Construction, RUP: Test

#154 fix: session color value
  src/App.vue
Labels: bug, Phase: Construction, RUP: Implementation

#158 feat: notification component
  src/App.vue
  src/components/ToastNotification/ToastNotification.vue
  src/composables/useNotificationSystem.ts
Labels: Phase: Construction, RUP: Implementation, improvement

#156 feat: unit and component tests
  src/components/LogOutput/LogOutput.test.ts
  src/components/MainVideoStream/MainVideoStream.vue
  src/components/MainVideoStream/Rectangle.ts
  src/components/ViewComponent/ViewComponent.test.ts
  src/components/capture-area/CaptureAreaSearchValue/CaptureAreaSearchValue.test.ts
  src/components/capture-area/CaptureAreaSearchValue/CaptureAreaSearchValue.vue
  src/components/capture-area/CaptureAreaSearchValue/ResetSettings.ts
  src/components/capture-area/RegexTextField/RegexTextField.test.ts
  src/composables/useForceRerender.test.ts
  src/composables/useNotificationSystem.test.ts
  src/main.ts
  src/plugins/vuetify/vuetify.ts
  src/plugins/vuetify/webfontloader.ts
  vite.config.ts
Labels: Phase: Construction, RUP: Test

#166 Fix: Refactored App.vue
  package-lock.json
  package.json
  src/App.vue
  src/components/LogOutput/LogOutput.vue
  src/components/MainVideoStream/MainVideoStream.vue
  src/components/Navigation/Navigation.vue
  src/components/Notifications/NotificationAnchorPosition.ts
  src/components/Notifications/NotificationPrompt/NotificationPrompt.vue
  src/components/Notifications/NotificationProvider/NotificationProvider.vue
  src/components/SettingsPrompt/SettingsPrompt.vue
  src/composables/useClipboard/useClipboard.test.ts
  src/composables/useClipboard/useClipboard.ts
  src/composables/useForceRerender/useForceRerender.test.ts
  src/composables/useForceRerender/useForceRerender.ts
  src/composables/useNotificationSystem/useNotificationSystem.test.ts
  src/composables/useNotificationSystem/useNotificationSystem.ts
  src/composables/useRunning/useRunning.ts
  src/composables/useTokenGenerator/useTokenGenerator.test.ts
  src/composables/useTokenGenerator/useTokenGenerator.ts
  src/views/CapturePage.vue
  src/views/RegexView.vue
Labels: Phase: Construction, RUP: Implementation, improvement

#170 feat(CI): enhance pipeline
  .github/workflows/main-test.yml
  .github/workflows/publish-build.yml
  .github/workflows/test-coverage.yml
  package.json
Labels: enhancement, Phase: Construction, RUP: Environment, RUP: Test

#171 feat: Used notification system in existing systems
  src/components/capture-area/CaptureAreaSearchValue/CaptureAreaSearchValue.vue
  src/composables/useRunning/useRunning.ts
  src/views/RegexView.vue
Labels: Phase: Construction, RUP: Implementation, improvement

#183 refactor: cleaned up old composables to follow proper conventions
  src/components/LogOutput/LogOutput.vue
  src/components/MainVideoStream/MainVideoStream.vue
  src/components/Navigation/Navigation.vue
  src/composables/useForceRerender/useForceRerender.test.ts
  src/composables/useForceRerender/useForceRerender.ts
  src/composables/useRunning/useRunning.ts
  src/views/CapturePage.vue
  src/views/RegexView.vue
Labels: Phase: Construction, RUP: Implementation, improvement

#181 feat: set default preview when stream can't be found anymore
  .vscode/extensions.json
  .vscode/settings.json
  electron/main/index.ts
  electron/preload/index.ts
  src/App.vue
  src/components/MainVideoStream/MainVideoStream.vue
  src/components/ViewComponent/ViewComponent.vue
  src/components/capture-area/CaptureAreaSearchValue/CaptureAreaSearchValue.vue
  src/composables/useStreamHandler/useStreamHandler.ts
  src/plugins/vuetify/vuetify.ts
  src/proc/StreamHandler.ts
  src/proc/Vigad.ts
  src/views/SourcesView.vue
Labels: bug, Phase: Construction, RUP: Implementation

#188 fix: formating for markdown files
  .github/ISSUE_TEMPLATE/new-issue.md
  .github/PULL_REQUEST_TEMPLATE.md
  .vscode/launch.json
  README.md
Labels: Phase: Construction, RUP: Implementation, improvement
